### ISSUE TITLE
Error on loading a second Caddyfile

### ISSUE THREAD

**Issue by deanishe** [isobit/vim-caddyfile#3]
If I load more than one Caddyfile without quitting vim first, I get the following error:

```
Error detected while processing [...]/indent/caddyfile.vim:
  1 line   17:
38  E122: Function <SNR>99_sw already exists, add ! to replace it
```

I'm not much good at vimscript. Should the definition perhaps use `func!`?

**Comment by deanishe** [comment]
Thanks very much. Works perfectly now!

**Comment by isobit** [comment]
No problem, thanks for the report. I'm surprised I didn't run into it earlier!
